version: '3.7'
services:
    db:
        image: mysql
        command: ["--default-authentication-plugin=mysql_native_password"]
        ports:
            - "3307:3306"
        volumes:
          - ./data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: dev_team_db
            MYSQL_USER: root
            MYSQL_PASSWORD: password

    smtp:
        image: djfarrelly/maildev
        container_name: sf4_maildev
        ports:
          - "8025:80"

    php:
        build: ./php-fpm
        ports:
            - "9000:9000"
        volumes:
            - .:/var/www/symfony:cached
            - ./logs:/var/www/symfony/var/log:cached
        links:
            - db
            - smtp
        environment:
            - maildev_host=sf4_maildev
        tty: true
        extra_hosts:
            - "docker.host:127.0.0.1"
    nginx:
        build: ./nginx
        ports:
            - "80:80"
        links:
            - php
        volumes:
            - ./logs/nginx:/var/log/nginx:cached
            - .:/var/www/symfony:cached